version: 'latest'

services:
  barstool:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio:latest
    container_name: portfolio
    ports:
      - "3003:3000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-http.rule=Host(`portfolio.jonasneu.de`)"
      - "traefik.http.routers.portfolio-http.entrypoints=http"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3003"
      - "traefik.http.routers.portfolio-https.rule=Host(`portfolio.jonasneu.de`)"
      - "traefik.http.routers.portfolio-https.entrypoints=https"
      - "traefik.http.routers.portfolio-https.tls=true"
      - "traefik.http.routers.portfolio-https.tls.certresolver=http"

networks:
  proxy:
    external: true